# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Raúl Vílchez Ruiz <raulmicrosistemas@gmail.com>
#
# Makefile - Build instructions for hwnet-io
#


obj-m += sysfs_driver.o

# Cabeceras del proyecto
ccflags-y := -I$(src)/../../include -I$(src)/../core