# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Raúl Vílchez Ruiz <raulmicrosistemas@gmail.com>
#
# Makefile - Build instructions for hwbus-io
#
DRIVER_DIR ?= ../driver

obj-m += hwnet_io.o
hwnet_io-y := main.o

# obj-m += mi_modulo.o
# mi_modulo-y := hello.o otro.o otro_mas.o

# Cabeceras del proyecto
ccflags-y := -I$(src)/../../include